import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: { flex: 1, alignItems: "center" },
  background: { width: "100%", height: "100%", alignItems: "center" },
  buttonContainer: {
    marginTop: 30,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 4, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 15,
    elevation: 10,
    borderRadius: 100,
    borderWidth: 5,
    borderColor: "#c9a93d",
    overflow: "hidden",
  },
  textBalance: {
    color: "white",
    fontSize: 18,
    fontWeight: "900",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
    letterSpacing: 2,
  },
  show: {
    backgroundColor: "rgba(255, 255, 0, 0.5)",
    width: "100%",
    height: "100%",
    position: "absolute",
    top: "0%",
    zIndex: 100,
  },
  bid: {
    backgroundColor: "black",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 110,
    position: "absolute",
    top: "28%",
    borderColor: "#c9a93d",
    borderWidth: 2,
    padding: 10,
    width: "90%",
  },
  card: {
    margin: 24,
    padding: 28,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 10,
    alignItems: "center",
    backgroundColor: "#fff",
    position: "absolute",
    top: "30%",
    zIndex: 100,
    width: "85%",
    alignSelf: "center",
    borderColor: "#c0392b",
    borderWidth: 3,
  },
  title: {
    fontSize: 32,
    fontWeight: "900",
    color: "#34495e",
    marginBottom: 14,
    textAlign: "center",
  },
  message: {
    fontSize: 18,
    color: "#2c3e50",
    textAlign: "center",
    marginBottom: 24,
  },
  gradient: {
    paddingVertical: 10,
    paddingHorizontal: 30,
    width: "100%",
    resizeMode: "contain", // gold border
  },
  innerShadow: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 2,
  },
  text: {
    color: "white",
    fontSize: 32,
    fontWeight: "900",
    textShadowColor: "#000",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 2,
    letterSpacing: 2,
  },
  triangle: { position: "absolute", top: "0%", zIndex: 1 },
  coin: { color: "white", fontSize: 20 },
  button: { borderColor: "#c9a93d", borderWidth: 2, width: "50%", alignItems: "center", margin: 10, padding: 5 },
  next: {
    margin: 10,

    justifyContent: "center",
    borderColor: "#c9a93d",
    borderWidth: 2,
  },
});
export default styles;
